mode: interactive  # 'interactive', 'script', or 'daemon'; can be overriden by CLI arg
log-level: info  # 'debug', 'info', 'error'

sources:
  sample:
    video: resources/SampleVideo_360x240_5mb.mp4
    subs: resources/SampleVideo.srt

output:
  filename: output.jpg

  imgur:
    enabled: true
    # See: https://apidocs.imgur.com/#c85c9dfc-7487-4de2-9ecd-66f727cf3139    
    client-id: XXX-PLACEHOLDER-XXX
  
  reddit:
    enabled: true  # also requires imgur enabled
    # See: https://praw.readthedocs.io/en/latest/getting_started/authentication.html#password-flow
    client-id: XXX-PLACEHOLDER-XXX
    client-secret: XXX-PLACEHOLDER-XXX
    username: XXX-PLACEHOLDER-XXX
    password: XXX-PLACEHOLDER-XXX
    
daemon:
  interval-seconds: 3600  # 1 hour